Project/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Project.Models
{
    [Table("Contact")]
    public class Contact
    {
        [Key]
        public int  ID { get; set; }
        public String firtName { get; set; }
        public String LastName { get; set; }

        public String email { get; set; }
        public String Subject { get; set; }
        public String Message { get; set; }

        public int Status { get; set; }

        public DateTime CreateDate { get; set; }

    }
}

Project/Areas/Admin/Controllers/ContactsController.cs
using Project.DBcontext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Areas.Admin.Controllers
{
    public class ContactsController : Controller
    {
        // GET: Admin/Contacts
        public ActionResult Index()
        {
            SugasContext sc = new SugasContext();
            var list = sc.Contacts.OrderByDescending(x=>x.CreateDate).ToList();
            return View(list);
        }

        public ActionResult Status(int status , int id)
        {
            SugasContext sc = new SugasContext();
            var contact = sc.Contacts.Where(x => x.ID == id).FirstOrDefault();
            if(status == 0)
            {
                contact.Status = 1;
            }
            else
            {
                contact.Status = 0;
            }
            sc.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Detail(int id)
        {
            SugasContext sc = new SugasContext();
            var contact = sc.Contacts.Where(x => x.ID == id).FirstOrDefault();
            return View(contact);
        }
    }
}

Project/Controllers/CategoryController.cs
using Project.DBcontext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{

    public class CategoryController : Controller
    {
        SugasContext sugasContext = new SugasContext();
        // GET: Category

        public ActionResult Index()
        {

            return View();

        }
        public PartialViewResult GetCategory()
        {
            var category = sugasContext.Categories.OrderBy(x => x.CategoryName).ToList();


            return PartialView(category);
        }
        public PartialViewResult GetLatestCategory()
        {
            var category = sugasContext.Categories.OrderBy(x => x.CategoryName).ToList();


            return PartialView(category);
        }
    }
}

Project/Controllers/HomeController.cs
using Project.DBcontext;
using Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
       public ActionResult AddContact(Contact contact)
        {
            SugasContext sc = new SugasContext();
            Contact c = new Contact();
            c.firtName = contact.firtName;
            c.LastName = contact.LastName;
            c.Message = contact.Message;
            c.Subject = contact.Subject;
            c.email = contact.email;
            c.Status = 0;
            c.CreateDate = DateTime.Now;
            sc.Contacts.Add(c);
            sc.SaveChanges();

            String subject = "Have Message's contact";
            String body = $"A Customer have been send messages to concact" ;
            WebMail.Send("nguyenquangdat199999@gmail.com", subject, body, null, null, null, true, null, null, null, null, null);
            return Json(data:"Send Message Sucessfuly",JsonRequestBehavior.AllowGet);
        }
    }
}

Project/Controllers/ProductController.cs
using Project.DBcontext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using PagedList;

namespace Project.Controllers
{

    public class ProductController : Controller
    {
        SugasContext sugasContext = new SugasContext();
        // GET: Product
        public ActionResult Index(int? page, string searchBy, string search)
        {

            if (page == null) page = 1;

            var products = sugasContext.Products.OrderBy(x => x.ProductID);

            int pageSize = 8;

            int pageNumber = (page ?? 1);

            if (searchBy == "NameProduct")
            {
                return View(sugasContext.Products.Where(s => s.ProductName.StartsWith(search)).OrderByDescending(s => s.ProductID).ToPagedList(pageNumber, pageSize));
            }

            // 5. Trả về các sản phẩm được phân trang theo kích thước và số trang.
            return View(products.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult GetLastestProduct()
        {
            var product = sugasContext.Products.Where(p => p.IsNewProduct == true)
                           .OrderByDescending(p => p.ProductDate).Take(8).ToList();
            return PartialView(product);
        }
        public ActionResult GetLastestProductByCategory(int? page, int? category)
        {
            if (page == null) page = 1;

            var products = sugasContext.Products.OrderBy(x => x.ProductID);

            int pageSize = 4;

            int pageNumber = (page ?? 1);

            if (category != null)
            {

                ViewBag.category = category;
                var product = sugasContext.Products.OrderByDescending(x => x.ProductDate).Where(x => x.CategoryID == category).ToPagedList(pageNumber, pageSize);
                return PartialView(product);
            }
            else
            {
                var productlist = sugasContext.Products.OrderByDescending(x => x.ProductDate).ToPagedList(pageNumber, pageSize);
                return PartialView(productlist);
            }
        }
        public ActionResult Details(int productID = 0)
        {
            var detail = sugasContext.Products.SingleOrDefault(n => n.ProductID == productID);
            if (detail == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(detail);
        }
        public ActionResult ProductByCategory(int? page, int? category)
        {
            {
                if (page == null) page = 1;

                int pageSize = 4;

                int pageNumber = (page ?? 1);

                if (category != null)
                {
                    ViewBag.Category = category;
                    var product = sugasContext.Products.OrderBy(x => x.ProductID).Where(x => x.CategoryID == category);
                    return View(product.ToPagedList(pageNumber, pageSize));
                }
                else
                {
                    return RedirectToAction("index", "Error");
                }
            }
        }
            Dictionary<Product, int> cart = null;
            public ActionResult addToCart(int productID)
            {
                // lấy sản phẩm từ web
                var detail = sugasContext.Products.SingleOrDefault(n => n.ProductID == productID);
                if (detail == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                else
                {
                    cart = (Dictionary<Product, int>)Session["Cart"];
                    if (cart == null)
                    {
                        cart = new Dictionary<Product, int>();
                        cart.Add(detail, 1);
                    }
                    else
                    { //nếu sản phẩm có trong kho thì add to cart
                        for (int index = 0; index < cart.Count; index++)
                        {
                            var item = cart.ElementAt(index);
                            var itemKey = item.Key;
                            var itemValue = item.Value;
                            if (itemKey.ProductID == productID)
                            {
                                cart[itemKey]++;
                                return RedirectToAction("Index");
                            }
                        }

                        cart.Add(detail, 1);
                    }

                }
                Session.Add("Cart", cart);
                return RedirectToAction("Index");
                //
            }

        public ActionResult removeFromCart(int productID)
        {
            // lấy sản phẩm từ web
            var detail = sugasContext.Products.SingleOrDefault(n => n.ProductID == productID);
            if (detail == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            else
            {
                cart = (Dictionary<Product, int>)Session["Cart"];
                if (cart != null)
                {
                    for (int index = 0; index < cart.Count; index++)
                    {
                        var item = cart.ElementAt(index);
                        var itemKey = item.Key;
                        var itemValue = item.Value;
                        if (itemKey.ProductID == productID)
                        {
                            cart.Remove(item.Key);
                        }
                    }
                }
            }
            Session.Add("Cart", cart);
            return RedirectToAction("Index");
            //
        }
        public ActionResult checkOut()
        {
            User u = (User)Session["use"];
            if (u != null)
            {
                var cart = (Dictionary<Product, int>)Session["Cart"];
                if (cart != null)
                {


                    for (int index = 0; index < cart.Count; index++)
                    {
                        var item = cart.ElementAt(index);
                        var itemKey = item.Key;
                        var itemValue = item.Value;
                        Order o = new Order();
                        o.pid = itemKey.ProductID;
                        o.price = itemKey.ProductPrice;
                        o.quantity = itemValue;
                        o.time = DateTime.Now;
                        o.uid = u.UserID;
                        o.total = itemValue * (int)itemKey.ProductPrice;
                        o.status = "Pending";
                        sugasContext.Orders.Add(o);
                        sugasContext.SaveChanges();
                    }

                    Session.Remove("Cart");
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }





    }
}

Project/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Project/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<section class="page-add">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="page-breadcrumb">
                    <h2>Contact us<span>.</span></h2>
                </div>
            </div>
            <div class="col-lg-8">
                <img src="img/add.jpg" alt="">
            </div>
        </div>
    </div>
</section>
<!-- Page Add Section End -->
<!-- Contact Section Begin -->
<div class="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <form action="#" class="contact-form">
                    <div class="row">
                        <div class="col-lg-6">
                            <input type="text" placeholder="First Name" id="firtname">
                        </div>
                        <div class="col-lg-6">
                            <input type="text" placeholder="Last Name" id="lastname">
                        </div>
                        <div class="col-lg-12">
                            <input type="email" placeholder="E-mail" id="email">
                            <input type="text" placeholder="Subject" id="subject">
                            <textarea placeholder="text" id="message"></textarea>
                        </div>
                        <div class="col-lg-12 text-right">
                            <button type="submit" id="btnSendata">Send message</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 offset-lg-1">
                <div class="contact-widget">
                    <div class="cw-item">
                        <h5>Location</h5>
                        <ul>
                            <li>FPT University </li>
                            <li>HaNoi, VietNam</li>
                        </ul>
                    </div>
                    <div class="cw-item">
                        <h5>Phone</h5>
                        <ul>
                            <li>+84 94 84 83 85 6</li>
                            <li>+(024)7308.13.13</li>
                        </ul>
                    </div>
                    <div class="cw-item">
                        <h5>E-mail</h5>
                        <ul>
                            <li>contact@sugasclothes.com</li>
                            <li>www.sugasclothes.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="map">
            <div class="row">
                <div class="col-lg-12">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26440.72384129847!2d-118.24906619231132!3d34.06719475913053!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c659f50c318d%3A0xe2ffb80a9d3820ae!2sChinatown%2C%20Los%20Angeles%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1570213740685!5m2!1sen!2sbd"
                            height="560" style="border:0;" allowfullscreen=""></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

Project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@model IEnumerable<Project.Models.Product>

<!-- Features Section Begin -->
<section class="features-section spad">
    <div class="features-ads">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="single-features-ads first">
                        <img src="~/Content/img/icons/f-delivery.png" alt="">
                        <h4>Free shipping</h4>
                        <p>
                            Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal
                            esuada aliquet libero viverra cursus.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-features-ads second">
                        <img src="~/Content/img/icons/coin.png" alt="">
                        <h4>100% Money back </h4>
                        <p>
                            Urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal esuada
                            aliquet libero viverra cursus.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-features-ads">
                        <img src="~/Content/img/icons/chat.png" alt="">
                        <h4>Online support 24/7</h4>
                        <p>
                            Urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal esuada
                            aliquet libero viverra cursus.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Features Box -->
    <div class="features-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="single-box-item first-box">
                                <img src="~/Content/img/f-box-1.jpg" alt="">
                                <div class="box-text">
                                    <span class="trend-year">2019 Party</span>
                                    <h2>Jewelry</h2>
                                    <span class="trend-alert">Trend Allert</span>
                                    <a href="https://www.tiffany.com/jewelry/" class="primary-btn">See More</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="single-box-item second-box">
                                <img src="~/Content/img/f-box-2.jpg" alt="">
                                <div class="box-text">
                                    <span class="trend-year">2019 Trend</span>
                                    <h2>Footwear</h2>
                                    <span class="trend-alert">Bold & Black</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="single-box-item large-box">
                        <img src="~/Content/img/f-box-3.jpg" alt="">
                        <div class="box-text">
                            <span class="trend-year">2019 Party</span>
                            <h2>Collection</h2>
                            <div class="trend-alert">Trend Allert</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Features Section End -->
<!-- Latest Product Begin -->
<section class="latest-products spad">
    <div class="container">
        <div class="product-filter">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-title">
                        <h2>Latest Products</h2>
                    </div>
                    <ul class="product-controls">
                        @Html.Action("GetCategory", "Category")
                    </ul>
                </div>
            </div>
        </div>

        <div class="row" id="product-list">
            @{
                Html.RenderAction("GetLastestProduct", "Product");
            
                
            }
            @*<div class="col-lg-3 col-sm-6 mix all dresses bags">
            <div class="single-product-item">
                <figure>
                    <a href="#"><img src="~/Content/img/products/img-1.jpg" alt=""></a>
                    <div class="p-status">new</div>
                </figure>
                <div class="product-text">
                    <h6>Green Dress with details</h6>
                    <p>$22.90</p>
                </div>
            </div>
        </div>*@

            @*<div class="col-lg-3 col-sm-6 mix all dresses bags">
                <div class="single-product-item">
                    <figure>
                        <a href="#"><img src="~/Content/img/products/img-2.jpg" alt=""></a>
                        <div class="p-status sale">sale</div>
                    </figure>
                    <div class="product-text">
                        <h6>Yellow Maxi Dress</h6>
                        <p>$25.90</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 mix all shoes accesories">
                <div class="single-product-item">
                    <figure>
                        <a href="#"><img src="~/Content/img/products/img-3.jpg" alt=""></a>
                        <div class="p-status">new</div>
                    </figure>
                    <div class="product-text">
                        <h6>One piece bodysuit</h6>
                        <p>$19.90</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 mix all shoes accesories">
                <div class="single-product-item">
                    <figure>
                        <a href="#"><img src="~/Content/img/products/img-4.jpg" alt=""></a>
                        <div class="p-status popular">popular</div>
                    </figure>
                    <div class="product-text">
                        <h6>Blue Dress with details</h6>
                        <p>$35.50</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 mix all dresses shoes">
                <div class="single-product-item">
                    <figure>
                        <a href="#"><img src="~/Content/img/products/img-5.jpg" alt=""></a>
                        <div class="p-status">new</div>
                    </figure>
                    <div class="product-text">
                        <h6>Green Dress with details</h6>
                        <p>$22.90</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 mix all accesories bags">
                <div class="single-product-item">
                    <figure>
                        <a href="#"><img src="~/Content/img/products/img-6.jpg" alt=""></a>
                        <div class="p-status sale">sale</div>
                    </figure>
                    <div class="product-text">
                        <h6>Yellow Maxi Dress</h6>
                        <p>$25.90</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 mix all dresses bags">
                <div class="single-product-item">
                    <figure>
                        <a href="#"><img src="~/Content/img/products/img-7.jpg" alt=""></a>
                    </figure>
                    <div class="product-text">
                        <h6>One piece bodysuit</h6>
                        <p>$19.90</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 mix all accesories bags">
                <div class="single-product-item">
                    <figure>
                        <a href="#"><img src="~/Content/img/products/img-8.jpg" alt=""></a>
                        <div class="p-status popular">popular</div>
                    </figure>
                    <div class="product-text">
                        <h6>Blue Dress with details</h6>
                        <p>$35.50</p>
                    </div>
                </div>
            </div>
        </div>*@
        </div>
    </div>
</section>
<!-- Latest Product End -->
<!-- Lookbok Section Begin -->
<section class="lookbok-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4 offset-lg-1">
                <div class="lookbok-left">
                    <div class="section-title">
                        <h2>2019 <br />#lookbook</h2>
                    </div>
                    <p>
                        Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vestibulum malesuada
                        aliquet libero viverra cursus. Aliquam erat volutpat. Morbi id dictum quam, ut commodo
                        lorem. In at nisi nec arcu porttitor aliquet vitae at dui. Sed sollicitudin nulla non leo
                        viverra scelerisque. Phasellus facilisis lobortis metus, sit amet viverra lectus finibus ac.
                        Aenean non felis dapibus, placerat libero auctor, ornare ante. Morbi quis ex eleifend,
                        sodales nulla vitae, scelerisque ante. Nunc id vulputate dui. Suspendisse consectetur rutrum
                        metus nec scelerisque. s
                    </p>
                    <a href="#" class="primary-btn look-btn">See More</a>
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="lookbok-pic">
                    <img src="~/Content/img/lookbok.jpg" alt="">
                    <div class="pic-text">fashion</div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Lookbok Section End -->
<!-- Logo Section Begin -->
<div class="logo-section spad">
    <div class="logo-items owl-carousel">
        <div class="logo-item">
            <img src="~/Content/img/logos/logo-1.png" alt="">
        </div>
        <div class="logo-item">
            <img src="~/Content/img/logos/logo-2.png" alt="">
        </div>
        <div class="logo-item">
            <img src="~/Content/img/logos/logo-3.png" alt="">
        </div>
        <div class="logo-item">
            <img src="~/Content/img/logos/logo-4.png" alt="">
        </div>
        <div class="logo-item">
            <img src="~/Content/img/logos/logo-5.png" alt="">
        </div>
    </div>
</div>