Project/Areas/Admin/Controllers/RolesController.cs
using OfficeOpenXml;
using Project.DBcontext;
using Project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace Project.Areas.Admin.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class RolesController : Controller
    {
        private SugasContext sugasContext = new SugasContext();

        // GET: Admin/Roles
        // Reuturn List of Role in View Index
        public ActionResult Index()
        {

            return View(sugasContext.Roles.ToList());
        }

        // GET: Admin/Roles/Details
        // Reuturn Details of Role by ID in Detalis Index
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roles roles = sugasContext.Roles.Find(id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            return View(roles);
        }

        // GET: Admin/Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoleID,RoleName")] Roles roles)
        {
            if (ModelState.IsValid)
            {
                sugasContext.Roles.Add(roles);
                sugasContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(roles);
        }

        // GET: Admin/Roles/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roles roles = sugasContext.Roles.Find(id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            return View(roles);
        }

        // POST: Admin/Roles/Edit
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoleID,RoleName")] Roles roles)
        {
            if (ModelState.IsValid)
            {
                sugasContext.Entry(roles).State = EntityState.Modified;
                sugasContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roles);
        }

        // GET: Admin/Roles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roles roles = sugasContext.Roles.Find(id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            return View(roles);
        }

        // POST: Admin/Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Roles roles = sugasContext.Roles.Find(id);
            sugasContext.Roles.Remove(roles);
            sugasContext.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
               sugasContext.Dispose();
            }
            base.Dispose(disposing);
        }

        public void ExportToExcel()
        {
            var roles = sugasContext.Roles.ToList();

            ExcelPackage.LicenseContext = LicenseContext.Commercial;
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            ExcelPackage excelPackage = new ExcelPackage();
            //add new ExcelSheet
            ExcelWorksheet ws = excelPackage.Workbook.Worksheets.Add("Report");
            // process our database dât in excelSheet
            ws.Cells["A1"].Value = "Report";
            ws.Cells["B1"].Value = "Report1";

            ws.Cells["A2"].Value = "Date";
            ws.Cells["B2"].Value = string.Format("{0:dd MMM yyy} at {0:H: mm tt}", DateTimeOffset.Now);

            ws.Cells["A5"].Value = "RoleID";
            ws.Cells["B5"].Value = "RoleName";




            int rows = 6;
            foreach (var item in roles)
            {
                ws.Cells[String.Format("A{0}", rows)].Value = item.RoleID;
                ws.Cells[String.Format("B{0}", rows)].Value = item.RoleName;

                rows++;

            }

            ws.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposittion", "attachment: filename=" + "ExcelReport.xlsx");
            Response.BinaryWrite(excelPackage.GetAsByteArray());
            Response.End();
        }
    }
}

Project/Areas/Admin/Controllers/TagsController.cs
using OfficeOpenXml;
using Project.DBcontext;
using Project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Project.Areas.Admin.Controllers
{
    public class TagsController : Controller
    {
        private SugasContext sugasContext = new SugasContext();
        // GET: Admin/Tag
        public ActionResult Index()
        {
            return View(sugasContext.Tags.ToList());
        }

        // GET: Admin/Hedieuhanhs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = sugasContext.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // GET: Admin/Hedieuhanhs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Hedieuhanhs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TagID,TagName")] Tags tags)
        {
            if (ModelState.IsValid)
            {
                sugasContext.Tags.Add(tags);
                sugasContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tags);
        }

        // GET: Admin/Hedieuhanhs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = sugasContext.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }


        // POST: Admin/Hedieuhanhs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TagID,TagName")] Tags tags)
        {
            if (ModelState.IsValid)
            {
                sugasContext.Entry(tags).State = EntityState.Modified;
                sugasContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tags);
        }

        // GET: Admin/Hedieuhanhs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = sugasContext.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // POST: Admin/Hedieuhanhs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tags tags = sugasContext.Tags.Find(id);
            sugasContext.Tags.Remove(tags);
            sugasContext.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                sugasContext.Dispose();
            }
            base.Dispose(disposing);
        }

        public void ExportToExcel()
        {
            var tags = sugasContext.Tags.ToList();

            ExcelPackage.LicenseContext = LicenseContext.Commercial;
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            ExcelPackage excelPackage = new ExcelPackage();
            //add new ExcelSheet
            ExcelWorksheet ws = excelPackage.Workbook.Worksheets.Add("Report");
            // process our database dât in excelSheet
            ws.Cells["A1"].Value = "Report";
            ws.Cells["B1"].Value = "Report1";

            ws.Cells["A2"].Value = "Date";
            ws.Cells["B2"].Value = string.Format("{0:dd MMM yyy} at {0:H: mm tt}", DateTimeOffset.Now);

            ws.Cells["A5"].Value = "TagID";
            ws.Cells["B5"].Value = "TagName";


            int rows = 6;
            foreach (var item in tags)
            {
                ws.Cells[String.Format("A{0}", rows)].Value = item.TagID;
                ws.Cells[String.Format("B{0}", rows)].Value = item.TagName;

                rows++;

            }

            ws.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposittion", "attachment: filename=" + "ExcelReport.xlsx");
            Response.BinaryWrite(excelPackage.GetAsByteArray());
            Response.End();
        }
    }
}

Project/Controllers/ProductController.cs
using Project.DBcontext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using PagedList;

namespace Project.Controllers
{

    public class ProductController : Controller
    {
        SugasContext sugasContext = new SugasContext();
        // GET: Product
        public ActionResult Index(int? page, string searchBy, string search)
        {

            if (page == null) page = 1;

            var products = sugasContext.Products.OrderBy(x => x.ProductID);

            int pageSize = 8;

            int pageNumber = (page ?? 1);

            if (searchBy == "NameProduct")
            {
                return View(sugasContext.Products.Where(s => s.ProductName.StartsWith(search)).OrderByDescending(s => s.ProductID).ToPagedList(pageNumber, pageSize));
            }

            // 5. Trả về các sản phẩm được phân trang theo kích thước và số trang.
            return View(products.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult GetLastestProduct()
        {
            var product = sugasContext.Products.Where(p => p.IsNewProduct == true)
                           .OrderByDescending(p => p.ProductDate).Take(8).ToList();
            return PartialView(product);
        }
        public ActionResult GetLastestProductByCategory(int? page, int? category)
        {
            if (page == null) page = 1;

            var products = sugasContext.Products.OrderBy(x => x.ProductID);

            int pageSize = 4;

            int pageNumber = (page ?? 1);

            if (category != null)
            {

                ViewBag.category = category;
                var product = sugasContext.Products.OrderByDescending(x => x.ProductDate).Where(x => x.CategoryID == category).ToPagedList(pageNumber, pageSize);
                return PartialView(product);
            }
            else
            {
                var productlist = sugasContext.Products.OrderByDescending(x => x.ProductDate).ToPagedList(pageNumber, pageSize);
                return PartialView(productlist);
            }
        }
        public ActionResult Details(int productID = 0)
        {
            var detail = sugasContext.Products.SingleOrDefault(n => n.ProductID == productID);
            if (detail == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(detail);
        }
        public ActionResult ProductByCategory(int? page, int? category)
        {
            {
                if (page == null) page = 1;

                int pageSize = 4;

                int pageNumber = (page ?? 1);

                if (category != null)
                {
                    ViewBag.Category = category;
                    var product = sugasContext.Products.OrderBy(x => x.ProductID).Where(x => x.CategoryID == category);
                    return View(product.ToPagedList(pageNumber, pageSize));
                }
                else
                {
                    return RedirectToAction("index", "Error");
                }
            }
        }
            Dictionary<Product, int> cart = null;
            public ActionResult addToCart(int productID)
            {
                // lấy sản phẩm từ web
                var detail = sugasContext.Products.SingleOrDefault(n => n.ProductID == productID);
                if (detail == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                else
                {
                    cart = (Dictionary<Product, int>)Session["Cart"];
                    if (cart == null)
                    {
                        cart = new Dictionary<Product, int>();
                        cart.Add(detail, 1);
                    }
                    else
                    { //nếu sản phẩm có trong kho thì add to cart
                        for (int index = 0; index < cart.Count; index++)
                        {
                            var item = cart.ElementAt(index);
                            var itemKey = item.Key;
                            var itemValue = item.Value;
                            if (itemKey.ProductID == productID)
                            {
                                cart[itemKey]++;
                                return RedirectToAction("Index");
                            }
                        }

                        cart.Add(detail, 1);
                    }

                }
                Session.Add("Cart", cart);
                return RedirectToAction("Index");
                //
            }

        public ActionResult removeFromCart(int productID)
        {
            // lấy sản phẩm từ web
            var detail = sugasContext.Products.SingleOrDefault(n => n.ProductID == productID);
            if (detail == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            else
            {
                cart = (Dictionary<Product, int>)Session["Cart"];
                if (cart != null)
                {
                    for (int index = 0; index < cart.Count; index++)
                    {
                        var item = cart.ElementAt(index);
                        var itemKey = item.Key;
                        var itemValue = item.Value;
                        if (itemKey.ProductID == productID)
                        {
                            cart.Remove(item.Key);
                        }
                    }
                }
            }
            Session.Add("Cart", cart);
            return RedirectToAction("Index");
            //
        }
        public ActionResult checkOut()
        {
            User u = (User)Session["use"];
            if (u != null)
            {
                var cart = (Dictionary<Product, int>)Session["Cart"];
                if (cart != null)
                {


                    for (int index = 0; index < cart.Count; index++)
                    {
                        var item = cart.ElementAt(index);
                        var itemKey = item.Key;
                        var itemValue = item.Value;
                        Order o = new Order();
                        o.pid = itemKey.ProductID;
                        o.price = itemKey.ProductPrice;
                        o.quantity = itemValue;
                        o.time = DateTime.Now;
                        o.uid = u.UserID;
                        o.total = itemValue * (int)itemKey.ProductPrice;
                        o.status = "Pending";
                        sugasContext.Orders.Add(o);
                        sugasContext.SaveChanges();
                    }

                    Session.Remove("Cart");
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }





    }
}

Project/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SugasClothes Admin</title>
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/bootstrap.css" rel="stylesheet" />*@
    <link href="~/Areas/Content/dist/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Content/scripts/scripts.js"></script>
    <style type="text/css">
        .menu1 {
            color: white;
            padding-left: 20px;
        }
    </style>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-success">
        <h3>@Html.ActionLink("SugasClothes", "Index", "Product", new { @class = "menu1" })</h3>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            @*<div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>*@
        </form>

        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/User/Logout">Log out</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading" style="color:white"> <h5>Manager</h5></div>
                        <div style="padding-left:20px">
                            @Html.ActionLink("Product", "Index", "Product")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Category", "Index", "Categories")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Tag", "Index", "Tags")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("User", "Index", "Users")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Role", "Index", "Roles")
                        </div>
                        <br/>
                        <div style="padding-left:20px">
                            @Html.ActionLink("Contact", "Index", "Contacts")
                        </div>
                        @*<a class="nav-link" href="Home">
            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
            Hãng sản xuất
        </a>*@
                    </div>
                </div>

                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Administrator
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Administrator</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Content/dist/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Content/dist/assets/demo/chart-area-demo.js"></script>
    <script src="~/Areas/Content/dist/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Content/dist/assets/demo/datatables-demo.js"></script>
</body>
</html>